branches:
  only:
  - master
language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get build-dep -y python-h5py
install:
  - pip install -U pip setuptools wheel tox-travis coveralls
script: tox
after_success:
  - coveralls
